### PR TITLE
iss-hipm-907-bug icon doesn't fit new design manual

### PR DESCRIPTION
**Pull request by BeisiXiong**
*changed all icons and logos into new ones which should follow our corporate guideline manual

### CODE REVIEW

**Comment by BeisiXiong** [comment]
FYI:I tried to solve the launching screen image blur problem by export JPEG image in high resolution, but even though t still looks a bit blur.

**Comment by SvenEV** [comment]
Hey, I just checked again and saw that the splash screen now has proper margins. Nice!

**Comment by BeisiXiong** [comment]
@SvenEV THX,Good to hear~ hah,should I merge the master into it first before you merge it into master?
 cause I noticed this branch is a bit out of date.

**Comment by SvenEV** [comment]
@BeisiXiong You can merge master into this branch and then also this branch into master to close the pull request.

**Comment by BeisiXiong** [comment]
@SvenEV ah.. okay. It's just..... usually ,in our team, it is the reviewer who merges approved PR into master. But anyway I can do that too.

**Comment by SvenEV** [comment]
@BeisiXiong Ah good to know! In Team Fox we did it the other way round 😃

**Comment by BeisiXiong** [comment]
@SvenEV  I just realized that from our conversation,haha. But anyway,I am updating this branch,after  checks all passed , you can merge it, if you haven't done till tonight ,I will do it later tonight, Thx😉

**Pull request merged**
