### PR TITLE
Iss hipm 792

### PR DESCRIPTION
**Pull request by sayantik**
To test the changes go to Karl der Grosse im Wandel der Zeit page number 22 and click on the more button, it should show additional information.

### CODE REVIEW

**Comment by sayantik** [comment]
Not commited merge conflicts as after merge with master, project does not compile successfully

**Comment by BeisiXiong** [comment]
I will take a look at it after you solve the conflicts here !(grabbed it 😄)

**Comment by sayantik** [comment]
@BeisiXiong I've resolved the conflicts now and even the problem mentioned earlier is sorted.

**Comment by BeisiXiong** [comment]
@sayantik good to hear,I will check this later!

**Comment by BeisiXiong** [comment]
I tested it on Android, it's working properly. But I still have one question, as you specified here, 
 according to the comment here https://atlassian-hip.cs.uni-paderborn.de/jira/browse/HIPM-792   'Button disappears if no additional pages needed'. By button do you mean the three-dot button ? if so, I don't see the button disappear after I click on no-additional-info pages.(or Did I just misunderstood the requirement?) 

BTW, there showed up another conflict ,might because of the updates of master branch. 
Another thing is,I'm afraid I couldn't merge it to master so far since ios simulator is not working so that I could't test it on ios.

**Comment by sayantik** [comment]
We can take a look at this on Monday together. Any updates on the Mac so far?

**Comment by BeisiXiong** [comment]
@sayantik not yet,Bjorn hasn't replied yet, will approach to him on Monday also. not a big problem

**Pull request merged**
