### PR TITLE
Iss hipm 902 infobubble

### PR DESCRIPTION
**Pull request by sayantik**
Task Description:
The graphic for the info bubble of markers on the map is a simple png-file. To make it better scalable with devices with higher resolution, it should be replaced by a SVG; optionally with a more fitting style. 
Task accomplished:
Used a vector diagram for android by converting SVG to VectorDrawable

### CODE REVIEW

**Comment by nataliefriese** [comment]
info_bubble

The Infobubble should be a bit larger since the close button has no padding anymore

**Comment by nataliefriese** [comment]
grafik
Still no padding on top of the close button

**Comment by sayantik** [comment]
Ah you meant padding on top. Sorry I just changed the right padding. I'll do it that way then.

**Comment by cbruegg** [comment]
@sayantik Is there any chance you could still switch to [Visual Studio for Mac](https://www.visualstudio.com/de/vs/visual-studio-mac/)? This PR has changed all spaces to tabs in `MainActivity.cs`, which e.g. in the end could make it more difficult to merge in the changes from the .NET Standard migration. Switching shouldn't be too much of a hassle, but if it would cause some trouble, I could also fix the format before merging this PR, if that would be easier?

**Comment by sayantik** [comment]
@cbruegg I think I can try to switch to VS for Mac. However, the changes on MainActivity.cs can be discarded I think(since I'm not really using it). But I get your point. So if it turns out to be a hassle, then maybe you could fix the formatting please. I'll let you know :)

**Pull request merged**
