### PR TITLE
Call achievements API to show achievements in profile section (HIPM-797)

### PR DESCRIPTION
**Pull request by cbruegg**
Changes:

- Implemented `AchievementFetcher` which downloads the user's achievements into the local databases, returning any newly acquired achievements
- Implemented `AchievementConverter` which handles the conversion of all achievement types
- Added a method to `DtoToModelConverter` that allows the caller to specifiy the ID of the created model explicitly. In addition, the caller can also use the `updateCurrent` parameter to specify that any existing entity with the same ID should be removed before
- Implemented `AchievementManager` to get all achievements from the local DB
- Implemented on-demand achievement image download/display (see `AchievementExtension.LoadImage`)
- Implemented `AchievementApiAccess`
- Changed `ContentApiClient` to support other `basePath`s than `ServerEndpoints.DatastoreApiPath`
- Added tests
- Removed some unused files from the repo

# Testing notes
If you want to test this PR, you can remove the `/Unlocked` part from the URL to just get all achievements from the API instead of just the ones the user has unlocked already.

### CODE REVIEW

**Comment by cbruegg** [comment]
Looks like the ReSharper command line tools on the TFS are outdated. I have pinged @SvenEV already to ask for a fix.

**Comment by cbruegg** [comment]
Thanks! It seems like that file is not referenced anywhere. Removing it
caused no compile errors and I believe it was not actually included in the
solution.

MKlemens <notifications@github.com> schrieb am Do., 26. Okt. 2017, 21:55:

**Comment by Resudo** [comment]
If you delete the mentioned VM the download of details for exhibits and routes shouldn't work anymore. So it's _probably_ better to keep it in the solution.

**Comment by cbruegg** [comment]
@Resudo I have just checked: The download screen still works fine. I believe the VM that is actually used is the `ExhibitRouteDownloadPageViewModel`. And like I said, the `ExhibitRouteDownloadViewModel` wasn't referenced anywhere and not even included in `HipMobileUI.csproj`.

**Comment by cbruegg** [comment]
Update: This needs another change since the ImageUrl property will be changed to an ID. **Don't merge.**

**Pull request merged**
