### PR TITLE
Iss hipm 891: Mock service implementations for server outages

### PR DESCRIPTION
**Pull request by cbruegg**
During app development, we sometimes had the problem of not being able to continue as soon as servers are down. This PR introduces mock services that can be enabled in the `Constants.cs`. Here's a summary of the changes:

1. Added mock audio file.
2. Fixed `CreateObject` in `RealmDataAccess` when invoked with `updateCurrent = true` - now actually updates the current value.
3. Fixed issue where multiple Realm instances can exist.
4. Updated Realm to v1.6.0.
5. Implemented `MockXYZApiAccess` classes.

Not all features will work as if the server's are up, but the app is generally usable now.

### CODE REVIEW

**Comment by sayantik** [comment]
screen shot 2018-01-27 at 12 52 57 pm for the 1st instance
screen shot 2018-01-27 at 1 00 00 pm
for the second instance

**Comment by cbruegg** [comment]
Thanks for testing! Unfortunately, I can reproduce neither of these issues.

1. Seems to be unrelated to this PR, since it's complaining about a malformed notification generated by the AudioPlayer. (The one that allows controlling the audio playback.) If you can reproduce the problem, maybe you can file an issue for it on JIRA.
2. I have also tried this and I also can't reproduce it. It's an `OutOfMemoryError`, which means that the app has been consuming too much RAM and has been killed by the system. This should not be related to my changes. Does this happen consistently every time you're posting a rating? If yes, does it also happen without my changes?

**Comment by sayantik** [comment]
So I re-tested your branch. First, I did the same steps on the master branch. All went well. Then I re-tested the same changes on your branch without changing the flag 'Use Mock Data' and all went well. But the moment I turn the flag to true and play the audio, I end up with the first error.I repeated it multiple times, re-installing the app each time and it occurred every time. We can take a look at it later together if you want. It might be specific to my simulator for all we know.
 However, the second error with the rating was not reproduced.

**Comment by cbruegg** [comment]
That's very interesting, let's take a look tomorrow.

**Pull request merged**
