### PR TITLE
Iss hipm 793: Achievements Overview finalization

### PR DESCRIPTION
**Pull request by cbruegg**
This PR introduces the following changes:

- Currently, only unlocked achievements were stored in the local DB. With this change, all achievements are stored and the unlocked ones have a flag `IsUnlocked` set to `true`.
- Additionally, the local DB now also stores the points associated with an achievement to allow for a total score to be computed
- Reformatted `Settings.cs`, added inner `Events` class to listen for changes of properties, currently only `IsLoggedIn` . This is necessary so achievements are only shown when the user is logged in.
- Register `IAchievementFetcher` instance in `IoCManager`
- Wire up new achievements overview with API
- Remove old achievements UI in profile section

### CODE REVIEW

**Comment by cbruegg** [comment]
The TFS is having severe issues, unfortunately. @SvenEV or @BeisiXiong, do you know what could be causing this?

23558166_10210345837784497_1898494002_o

**Comment by BeisiXiong** [comment]
I've never seen this issue before, but I noticed this occurred not only on your branch, it's been occurring since the day before yesterday, after Build Forms-Droid-CI Build__20171110.1  this one has failed. I am just guessing ,it's because of this file on master branch is still being occupied. But the file address seems pretty wired.. maybe we have to deal with it tomorrow.

**Comment by SvenEV** [comment]
I don't have a clue, sorry... Our builds in Team Fox don't have these issues

**Comment by sayantik** [comment]
If you could merge the new master once, then I think we'd be able to merge it now as the build issues have been sorted

**Pull request merged**
