### PR TITLE
iss-hipm-840-icon

### PR DESCRIPTION
**Pull request by BeisiXiong**

### CODE REVIEW

**Comment by cbruegg** [comment]
@nataliefriese Do you have that issue only with this branch or with other branches as well?

**Comment by sayantik** [comment]
@cbruegg  I merged the master to my pull request(792) and I've the same error as Natalie :(

**Comment by BeisiXiong** [comment]
@sayantik  I couldn't deploy on both devices after I created a new branch,even though I do not see the same error. I thought it's my environment or configuration problem. idk

**Comment by sayantik** [comment]
@cbruegg  yup did that for my branch and it did work. Thanks! :)

**Comment by BeisiXiong** [comment]
@sayantik @nataliefriese hey,girls. I merged master branch again,it's working fine locally,so I pushed it again as well. could one of you review it one more time plz? thx in advance >_-

**Pull request merged**
